export enum PrivilegeType {
  READ = 'READ',
  WRITE = 'WRITE',
  DASHBOARD_ADMIN = 'DASHBOARD_ADMIN',
  DASHBOARD_USER = 'DASHBOARD_USER',
  SCRATCH_WRITE = 'SCRATCH_WRITE',
  SCRATCH_READ = 'SCRATCH_READ',
  SCRATCH_ADMIN = 'SCRATCH_ADMIN'
}