/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AppVersionInfoDto } from '../models';
/**
 * AppVersionControllerApi - axios parameter creator
 * @export
 */
export const AppVersionControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The version is the first 8-characters of the SHA-1 commit hash of the master branch that this version was compiled from
         * @summary Retrieves current running application version, along with the enclave level and environment this instance is running in
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVersion: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/version`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppVersionControllerApi - functional programming interface
 * @export
 */
export const AppVersionControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * The version is the first 8-characters of the SHA-1 commit hash of the master branch that this version was compiled from
         * @summary Retrieves current running application version, along with the enclave level and environment this instance is running in
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVersion(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppVersionInfoDto>> {
            const localVarAxiosArgs = await AppVersionControllerApiAxiosParamCreator(configuration).getVersion(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AppVersionControllerApi - factory interface
 * @export
 */
export const AppVersionControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * The version is the first 8-characters of the SHA-1 commit hash of the master branch that this version was compiled from
         * @summary Retrieves current running application version, along with the enclave level and environment this instance is running in
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVersion(options?: any): AxiosPromise<AppVersionInfoDto> {
            return AppVersionControllerApiFp(configuration).getVersion(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppVersionControllerApi - interface
 * @export
 * @interface AppVersionControllerApi
 */
export interface AppVersionControllerApiInterface {
    /**
     * The version is the first 8-characters of the SHA-1 commit hash of the master branch that this version was compiled from
     * @summary Retrieves current running application version, along with the enclave level and environment this instance is running in
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppVersionControllerApiInterface
     */
    getVersion(options?: any): AxiosPromise<AppVersionInfoDto>;

}

/**
 * AppVersionControllerApi - object-oriented interface
 * @export
 * @class AppVersionControllerApi
 * @extends {BaseAPI}
 */
export class AppVersionControllerApi extends BaseAPI implements AppVersionControllerApiInterface {
    /**
     * The version is the first 8-characters of the SHA-1 commit hash of the master branch that this version was compiled from
     * @summary Retrieves current running application version, along with the enclave level and environment this instance is running in
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppVersionControllerApi
     */
    public getVersion(options?: any) {
        return AppVersionControllerApiFp(this.configuration).getVersion(options).then((request) => request(this.axios, this.basePath));
    }
}
