/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AppSourceUsageDto } from './app-source-usage-dto';

/**
 * 
 * @export
 * @interface AppSourceUsageResponseDto
 */
export interface AppSourceUsageResponseDto {
    /**
     * 
     * @type {string}
     * @memberof AppSourceUsageResponseDto
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof AppSourceUsageResponseDto
     */
    endDate?: string;
    /**
     * 
     * @type {Array<AppSourceUsageDto>}
     * @memberof AppSourceUsageResponseDto
     */
    appSourceUsage?: Array<AppSourceUsageDto>;
}


