/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * App Source UUID
 * @export
 * @interface AppEndPointPrivDto
 */
export interface AppEndPointPrivDto {
    /**
     * 
     * @type {string}
     * @memberof AppEndPointPrivDto
     */
    appSourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof AppEndPointPrivDto
     */
    appEndpointId?: string;
    /**
     * 
     * @type {string}
     * @memberof AppEndPointPrivDto
     */
    appClientUserId?: string;
}


