/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ResourceAlreadyExistsExceptionCause } from './resource-already-exists-exception-cause';
import { ResourceAlreadyExistsExceptionCauseStackTrace } from './resource-already-exists-exception-cause-stack-trace';
import { ResourceAlreadyExistsExceptionCauseSuppressed } from './resource-already-exists-exception-cause-suppressed';

/**
 * 
 * @export
 * @interface BadRequestException
 */
export interface BadRequestException {
    /**
     * 
     * @type {ResourceAlreadyExistsExceptionCause}
     * @memberof BadRequestException
     */
    cause?: ResourceAlreadyExistsExceptionCause;
    /**
     * 
     * @type {Array<ResourceAlreadyExistsExceptionCauseStackTrace>}
     * @memberof BadRequestException
     */
    stackTrace?: Array<ResourceAlreadyExistsExceptionCauseStackTrace>;
    /**
     * 
     * @type {string}
     * @memberof BadRequestException
     */
    message?: string;
    /**
     * 
     * @type {Array<ResourceAlreadyExistsExceptionCauseSuppressed>}
     * @memberof BadRequestException
     */
    suppressed?: Array<ResourceAlreadyExistsExceptionCauseSuppressed>;
    /**
     * 
     * @type {string}
     * @memberof BadRequestException
     */
    localizedMessage?: string;
}


