/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MeterValueDto
 */
export interface MeterValueDto {
    /**
     * 
     * @type {string}
     * @memberof MeterValueDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MeterValueDto
     */
    appClient?: string;
    /**
     * 
     * @type {string}
     * @memberof MeterValueDto
     */
    metricName?: string;
    /**
     * 
     * @type {number}
     * @memberof MeterValueDto
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof MeterValueDto
     */
    timestamp?: string;
}


