/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RecordNotFoundExceptionCauseStackTrace } from './record-not-found-exception-cause-stack-trace';

/**
 * 
 * @export
 * @interface RecordNotFoundExceptionCauseSuppressed
 */
export interface RecordNotFoundExceptionCauseSuppressed {
    /**
     * 
     * @type {Array<RecordNotFoundExceptionCauseStackTrace>}
     * @memberof RecordNotFoundExceptionCauseSuppressed
     */
    stackTrace?: Array<RecordNotFoundExceptionCauseStackTrace>;
    /**
     * 
     * @type {string}
     * @memberof RecordNotFoundExceptionCauseSuppressed
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof RecordNotFoundExceptionCauseSuppressed
     */
    localizedMessage?: string;
}


