/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourceAlreadyExistsExceptionCauseStackTrace
 */
export interface ResourceAlreadyExistsExceptionCauseStackTrace {
    /**
     * 
     * @type {string}
     * @memberof ResourceAlreadyExistsExceptionCauseStackTrace
     */
    classLoaderName?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAlreadyExistsExceptionCauseStackTrace
     */
    moduleName?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAlreadyExistsExceptionCauseStackTrace
     */
    moduleVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAlreadyExistsExceptionCauseStackTrace
     */
    methodName?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAlreadyExistsExceptionCauseStackTrace
     */
    fileName?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceAlreadyExistsExceptionCauseStackTrace
     */
    lineNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceAlreadyExistsExceptionCauseStackTrace
     */
    className?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceAlreadyExistsExceptionCauseStackTrace
     */
    nativeMethod?: boolean;
}


