/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Privilege } from './privilege';
import { ScratchStorageUser } from './scratch-storage-user';

/**
 * 
 * @export
 * @interface ScratchStorageAppUserPriv
 */
export interface ScratchStorageAppUserPriv {
    /**
     * 
     * @type {string}
     * @memberof ScratchStorageAppUserPriv
     */
    id?: string;
    /**
     * 
     * @type {ScratchStorageUser}
     * @memberof ScratchStorageAppUserPriv
     */
    user?: ScratchStorageUser;
    /**
     * 
     * @type {Privilege}
     * @memberof ScratchStorageAppUserPriv
     */
    privilege?: Privilege;
}


