/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserWithPrivs } from './user-with-privs';

/**
 * 
 * @export
 * @interface ScratchStorageAppRegistryDto
 */
export interface ScratchStorageAppRegistryDto {
    /**
     * 
     * @type {string}
     * @memberof ScratchStorageAppRegistryDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ScratchStorageAppRegistryDto
     */
    appName: string;
    /**
     * 
     * @type {boolean}
     * @memberof ScratchStorageAppRegistryDto
     */
    appHasImplicitRead?: boolean;
    /**
     * 
     * @type {Array<UserWithPrivs>}
     * @memberof ScratchStorageAppRegistryDto
     */
    userPrivs?: Array<UserWithPrivs>;
}


