/* tslint:disable */
/* eslint-disable */
/**
 * TRON Common API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Field will only exist if there are validation errors
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    defaultMessage: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    objectName: string;
    /**
     * 
     * @type {object}
     * @memberof ValidationError
     */
    rejectedValue: object;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    fieldName: string;
}


